name = "Helm"
path_suffixes = ["yml", "yaml", "tpl"]
line_comments = ["# ", "// "]
block_comment = ["/*", "*/"]
autoclose_before = ",}]"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["comment", "string"] },
]

increase_indent_pattern = ":\\s*[|>]?\\s*$"

prettier_parser_name = "helm"